version: '3.8'

services:
  app:
    image: node:alpine
    build: ./
    volumes:
      - ./:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
    environment:
      NODE_ENV: development
      DB_HOST: mariadb-container
      DB_NAME: shop
      DB_USER: dev
      DB_PASSWORD: password

  mariadb:
    build: mariadb:10.5
    container_name: mariadb-container
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shop
      MYSQL_USER: dev
      MYSQL_PASSWORD: password
  
volumes:
  db_data:
